#version 440
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;


struct Particle
{
<INSERT VARIABLES>
}

uniform float dt;
uniform float t;
uniform unsigned int ActiveParticles;

layout( std140, binding=6 ) buffer ParticleBuffer 
{
	struct Particle Particles [];
};

void main ()
{
	unsigned int index = gl_GlobalInvocationID;
	if (index >= ActiveParticles)
		return;
	<INSERT CODE>
}


