#include "Key.h"
#define NOMINMAX
#include <Windows.h>

namespace Tocs {
namespace Input {

	Key Key::Back       (key_back       );
	Key Key::Tab        (key_tab        );
	Key Key::Clear      (key_clear      );
	Key Key::Return     (key_return     );
	Key Key::Shift      (key_shift      );
	Key Key::Control    (key_control    );
	Key Key::Menu       (key_menu       );
	Key Key::Pause      (key_pause      );
	Key Key::Capital    (key_capital    );
	Key Key::Escape     (key_escape     );
	Key Key::Convert    (key_convert    );
	Key Key::Nonconvert (key_nonconvert );
	Key Key::Accept     (key_accept     );
	Key Key::Modechange (key_modechange );
	Key Key::Space      (key_space      );
	Key Key::Prior      (key_prior      );
	Key Key::Next       (key_next       );
	Key Key::End        (key_end        );
	Key Key::Home       (key_home       );
	Key Key::Left       (key_left       );
	Key Key::Up         (key_up         );
	Key Key::Right      (key_right      );
	Key Key::Down       (key_down       );
	Key Key::Select     (key_select     );
	Key Key::Print      (key_print      );
	Key Key::Execute    (key_execute    );
	Key Key::Snapshot   (key_snapshot   );
	Key Key::Insert     (key_insert     );
	Key Key::Delete     (key_delete     );
	Key Key::Help       (key_help       );
	Key Key::Lwin       (key_lwin       );
	Key Key::Rwin       (key_rwin       );
	Key Key::Apps       (key_apps       );
	Key Key::Sleep      (key_sleep      );
	Key Key::Numpad0    (key_numpad0    );
	Key Key::Numpad1    (key_numpad1    );
	Key Key::Numpad2    (key_numpad2    );
	Key Key::Numpad3    (key_numpad3    );
	Key Key::Numpad4    (key_numpad4    );
	Key Key::Numpad5    (key_numpad5    );
	Key Key::Numpad6    (key_numpad6    );
	Key Key::Numpad7    (key_numpad7    );
	Key Key::Numpad8    (key_numpad8    );
	Key Key::Numpad9    (key_numpad9    );
	Key Key::Multiply   (key_multiply   );
	Key Key::Add        (key_add        );
	Key Key::Separator  (key_separator  );
	Key Key::Subtract   (key_subtract   );
	Key Key::Decimal    (key_decimal    );
	Key Key::Divide     (key_divide     );
	Key Key::F1         (key_f1         );
	Key Key::F2         (key_f2         );
	Key Key::F3         (key_f3         );
	Key Key::F4         (key_f4         );
	Key Key::F5         (key_f5         );
	Key Key::F6         (key_f6         );
	Key Key::F7         (key_f7         );
	Key Key::F8         (key_f8         );
	Key Key::F9         (key_f9         );
	Key Key::F10        (key_f10        );
	Key Key::F11        (key_f11        );
	Key Key::F12        (key_f12        );
	Key Key::F13        (key_f13        );
	Key Key::F14        (key_f14        );
	Key Key::F15        (key_f15        );
	Key Key::F16        (key_f16        );
	Key Key::F17        (key_f17        );
	Key Key::F18        (key_f18        );
	Key Key::F19        (key_f19        );
	Key Key::F20        (key_f20        );
	Key Key::F21        (key_f21        );
	Key Key::F22        (key_f22        );
	Key Key::F23        (key_f23        );
	Key Key::F24        (key_f24        );
	Key Key::Numlock    (key_numlock    );
	Key Key::Scroll     (key_scroll     );
	Key Key::Lshift     (key_lshift     );
	Key Key::Rshift     (key_rshift     );
	Key Key::Lcontrol   (key_lcontrol   );
	Key Key::Rcontrol   (key_rcontrol   );
	Key Key::Lmenu      (key_lmenu      );
	Key Key::Rmenu      (key_rmenu      );
	Key Key::Oem_1      (key_oem_1      );
	Key Key::Oem_plus   (key_oem_plus   );
	Key Key::Oem_comma  (key_oem_comma  );
	Key Key::Oem_minus  (key_oem_minus  );
	Key Key::Oem_period (key_oem_period );
	Key Key::Oem_2      (key_oem_2      );
	Key Key::Oem_3      (key_oem_3      );
	Key Key::Oem_4      (key_oem_4      );
	Key Key::Oem_5      (key_oem_5      );
	Key Key::Oem_6      (key_oem_6      );
	Key Key::Oem_7      (key_oem_7      );
	Key Key::Oem_8      (key_oem_8      );
	Key Key::Oem_ax     (key_oem_ax     );
	Key Key::Oem_102    (key_oem_102    );
	Key Key::Ico_help   (key_ico_help   );
	Key Key::Ico_00     (key_ico_00     );
	Key Key::Ico_clear  (key_ico_clear  );
	Key Key::Oem_reset  (key_oem_reset  );
	Key Key::Oem_jump   (key_oem_jump   );
	Key Key::Oem_pa1    (key_oem_pa1    );
	Key Key::Oem_pa2    (key_oem_pa2    );
	Key Key::Oem_pa3    (key_oem_pa3    );
	Key Key::Oem_wsctrl (key_oem_wsctrl );
	Key Key::Oem_cusel  (key_oem_cusel  );
	Key Key::Oem_attn   (key_oem_attn   );
	Key Key::Oem_finish (key_oem_finish );
	Key Key::Oem_copy   (key_oem_copy   );
	Key Key::Oem_auto   (key_oem_auto   );
	Key Key::Oem_enlw   (key_oem_enlw   );
	Key Key::Oem_backtab(key_oem_backtab);
	Key Key::Attn       (key_attn       );
	Key Key::Crsel      (key_crsel      );
	Key Key::Exsel      (key_exsel      );
	Key Key::Ereof      (key_ereof      );
	Key Key::Play       (key_play       );
	Key Key::Zoom       (key_zoom       );
	Key Key::Noname     (key_noname     );
	Key Key::Pa1        (key_pa1        );
	Key Key::Oem_clear  (key_oem_clear  );

	Key Key::A    (key_a);
	Key Key::B    (key_b);
	Key Key::C    (key_c);
	Key Key::D    (key_d);
	Key Key::E    (key_e);
	Key Key::F    (key_f);
	Key Key::G    (key_g);
	Key Key::H    (key_h);
	Key Key::I    (key_i);
	Key Key::J    (key_j);
	Key Key::K    (key_k);
	Key Key::L    (key_l);
	Key Key::M    (key_m);
	Key Key::N    (key_n);
	Key Key::O    (key_o);
	Key Key::P    (key_p);
	Key Key::Q    (key_q);
	Key Key::R    (key_r);
	Key Key::S    (key_s);
	Key Key::T    (key_t);
	Key Key::U    (key_u);
	Key Key::V    (key_v);
	Key Key::W    (key_w);
	Key Key::X    (key_x);
	Key Key::Y    (key_y);
	Key Key::Z    (key_z);
	Key Key::Num1 (key_1);
	Key Key::Num2 (key_2);
	Key Key::Num3 (key_3);
	Key Key::Num4 (key_4);
	Key Key::Num5 (key_5);
	Key Key::Num6 (key_6);
	Key Key::Num7 (key_7);
	Key Key::Num8 (key_8);
	Key Key::Num9 (key_9);
	Key Key::Num0 (key_0);

}}